[package]
name = "wrist"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13"
rayon = "1.10"
csv = "1.3"
colored = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
petgraph = "0.8.1"
anyhow = "1.0.98"